[package]
name = "day18"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "day18"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.75"
aoc = { path = "../aoc" }
